apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "env-route-ns-mutator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: env-route-ns-mutator
    app.kubernetes.io/part-of: env-route-ns-mutator
  {{- include "env-route-ns-mutator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "env-route-ns-mutator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "env-route-ns-mutator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}