apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "env-route-ns-mutator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "env-route-ns-mutator.fullname" . }}-serving-cert
  labels:
  {{- include "env-route-ns-mutator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "env-route-ns-mutator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-namespace
  failurePolicy: Ignore
  name: namespace.dana.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "env-route-ns-mutator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-route
  failurePolicy: Ignore
  name: route.dana.io
  rules:
  - apiGroups:
    - route.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - routes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "env-route-ns-mutator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-ingress
  failurePolicy: Ignore
  name: ingress.dana.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - ingresses
  sideEffects: None