apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "env-route-ns-mutator.fullname" . }}-proxy-rolebinding
  labels:
  {{- include "env-route-ns-mutator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "env-route-ns-mutator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "env-route-ns-mutator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}