apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "env-route-ns-mutator.fullname" . }}-serving-cert
  labels:
  {{- include "env-route-ns-mutator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "env-route-ns-mutator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "env-route-ns-mutator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "env-route-ns-mutator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert